### ISSUE TITLE
script doesnt work 

### ISSUE THREAD

**Issue by tahamarzak20** [rarecoil/unwebpack-sourcemap#23]
when i use the script i got this error 

Traceback (most recent call last):
  File "./unwebpack_sourcemap.py", line 362, in <module>
    extractor.run()
  File "./unwebpack_sourcemap.py", line 71, in run
    self._parse_remote_sourcemap(self._target)
  File "./unwebpack_sourcemap.py", line 95, in _parse_remote_sourcemap
    data, final_uri = self._get_remote_data(uri)
  File "./unwebpack_sourcemap.py", line 215, in _get_remote_data
    if self.disable_verify_ssl == True:
AttributeError: 'SourceMapExtractor' object has no attribute 'disable_verify_ssl'

**Comment by atsreejith** [comment]
if you are on windows, then navigate to the directory where you have the .py file, run the below command.
unwebpack_sourcemap.py --detect --disable-ssl-verification your_url_here output

**Comment by rarecoil** [comment]
This has been fixed in a recent version.
